version: '3.8'                                  # версия докера

services:                                       # сервисы, которые будут доступны в данном образе
  api:                                          # сервис под названием api
    build: ./api                                # из какого места искать dockerfile
    command: npm run start                      # какую команду выполнять после того как всё собралось
    restart: unless-stopped                     # перезапускать пока сам не остановлю работу контейнера
    ports:                                      # порты
      - "3000:3000"                             # порт снаружи:порт контейнера
    environment:                                # переменные окружения
      - PORT=3000                               # переменная PORT, доступная внутри контейнера app
      - HOST=http://realworld-docker.com        # переменная HOST, доступная внутри контейнера app
