version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:                                # с помощью этой строки, по идее, реакт должен перезагружать 
      - CHOKIDAR_USEPOLLING=true                # страницу при любых изменениях. но на момент урока, это не работает.

  api:
    command: npm run dev
    volumes:
      - "./api/src/:/usr/src/app/src/"

  auth:
    command: npm run dev
    volumes:
      - "./auth/src/:/usr/src/app/src/"

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf

#  команда для запуска dev файла:
#  docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
#  сначала берём конфиг основной, а потом переписываем ему команды из dev файла