version: '3.8'                                  # версия докера

services:                                       # сервисы, которые будут доступны в данном образе
  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    ports:
      - "3010:3000"
    restart: unless-stopped
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true                # с помощью этой строки, по идее, реакт должен перезагружать 
                                                # страницу при любых изменениях. но на момент урока, это не работает.

  api:                                          # сервис под названием api
    build: ./api                                # из какого места искать dockerfile
    container_name: realworld-docker-api        # название контейнера
    command: npm run start                      # какую команду выполнять после того как всё собралось
    restart: unless-stopped                     # перезапускать пока сам не остановлю работу контейнера
    ports:                                      # порты
      - "3001:3001"                             # порт снаружи:порт контейнера
    environment:                                # переменные окружения
      - PORT=3001                               # переменная PORT, доступная внутри контейнера app
      - HOST=http://realworld-docker.com        # переменная HOST, доступная внутри контейнера app
      - MONGO_URL=mongodb://api_db:27017/api    # адрес базы данных где api_db это название сервиса с базой вместо localhost
    depends_on:                                 # зависимости, после чего должен запускаться данный контейнер
      - api_db                                  # сначала должен запуститься контейнер с базой данных
  
  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
  
  api_db:                                       # сервис для базы данных mongodb
    image: mongo:latest                         # напрямую выбираем нужный образ mongodb
    container_name: realworld-docker-api-db     # название контейнера
    volumes:                                    # хранилища
      - mongodb_api:/data/db                    # сохраняем файлы базы данных в папке mongodb_api снаружи контейнера
  
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth: